# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wordservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11wordservice.proto\x12\x16\x65ndpoints.word_service\"\xb2\x01\n\x0eWordDefinition\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\x12\x0b\n\x03pos\x18\x03 \x01(\t\x12\x10\n\x08\x65xamples\x18\x04 \x03(\t\x12\x11\n\tsyllables\x18\x05 \x03(\t\x12\x16\n\x0eprobablyExists\x18\x06 \x01(\x08\x12\x34\n\x07\x64\x61taset\x18\x07 \x01(\x0e\x32#.endpoints.word_service.DatasetType\"j\n\x11\x44\x65\x66ineWordRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x34\n\x07\x64\x61taset\x18\x02 \x01(\x0e\x32#.endpoints.word_service.DatasetType\x12\x11\n\tdo_sample\x18\x03 \x01(\x08\"J\n\x12\x44\x65\x66ineWordResponse\x12\x34\n\x04word\x18\x01 \x01(\x0b\x32&.endpoints.word_service.WordDefinition\"B\n\x19WordFromDefinitionRequest\x12\x12\n\ndefinition\x18\x01 \x01(\t\x12\x11\n\tdo_sample\x18\x02 \x01(\x08\"R\n\x1aWordFromDefinitionResponse\x12\x34\n\x04word\x18\x01 \x01(\x0b\x32&.endpoints.word_service.WordDefinition\"\x15\n\x13GenerateWordRequest\"_\n\x14GenerateWordResponse\x12\x34\n\x04word\x18\x01 \x01(\x0b\x32&.endpoints.word_service.WordDefinition\x12\x11\n\tdo_sample\x18\x02 \x01(\x08*:\n\x0b\x44\x61tasetType\x12\x07\n\x03OED\x10\x00\x12\x0f\n\x0bUD_FILTERED\x10\x01\x12\x11\n\rUD_UNFILTERED\x10\x02\x32\xe0\x02\n\x0bWordService\x12\x65\n\nDefineWord\x12).endpoints.word_service.DefineWordRequest\x1a*.endpoints.word_service.DefineWordResponse\"\x00\x12}\n\x12WordFromDefinition\x12\x31.endpoints.word_service.WordFromDefinitionRequest\x1a\x32.endpoints.word_service.WordFromDefinitionResponse\"\x00\x12k\n\x0cGenerateWord\x12+.endpoints.word_service.GenerateWordRequest\x1a,.endpoints.word_service.GenerateWordResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wordservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATASETTYPE._serialized_start=682
  _DATASETTYPE._serialized_end=740
  _WORDDEFINITION._serialized_start=46
  _WORDDEFINITION._serialized_end=224
  _DEFINEWORDREQUEST._serialized_start=226
  _DEFINEWORDREQUEST._serialized_end=332
  _DEFINEWORDRESPONSE._serialized_start=334
  _DEFINEWORDRESPONSE._serialized_end=408
  _WORDFROMDEFINITIONREQUEST._serialized_start=410
  _WORDFROMDEFINITIONREQUEST._serialized_end=476
  _WORDFROMDEFINITIONRESPONSE._serialized_start=478
  _WORDFROMDEFINITIONRESPONSE._serialized_end=560
  _GENERATEWORDREQUEST._serialized_start=562
  _GENERATEWORDREQUEST._serialized_end=583
  _GENERATEWORDRESPONSE._serialized_start=585
  _GENERATEWORDRESPONSE._serialized_end=680
  _WORDSERVICE._serialized_start=743
  _WORDSERVICE._serialized_end=1095
# @@protoc_insertion_point(module_scope)
